### ISSUE TITLE
Import readline error

### ISSUE THREAD

**Issue by RamanaK** [marhar/aws#5]
Traceback (most recent call last):
  File "./awsh", line 9, in <module>
    import os,sys,readline,cmd,atexit,ConfigParser,traceback,subprocess,time
ImportError: No module named readline

**Comment by marhar** [comment]
I updated  README.md with instructions on how to build a Mac Python with working readline.  Try it and let me know if it works.

**Comment by RamanaK** [comment]
Thanks Mark, it's working fine now.
